#!/usr/bin/env python2
import rospy
from sensor_msgs.msg import JointState
from markers import *
import numpy as np
from robot_functions import *

if __name__ == '__main__':
 bmarker  = BallMarker(color['GREEN'])
 rospy.init_node("testForwardKinematics")
 pub = rospy.Publisher('joint_states', JointState, queue_size=1)
  
 # Joint names
 jnames = ['joint_1', 'joint_2', 'joint_3','joint_4', 'joint_5', 'joint_6','joint_7','joint_8']
 # Joint Configuration
 q  = np.array([ 2.48588849, -0.31285127, -0.16005493, -0.01715127,  0.40013112,  0.13598287,
  0.          ,0.        ])

 # End effector with respect to the base
 T = fkine(q)
 x0 = T[0:3,3]
 bmarker.xyz(x0)
 print( np.round(T, 3) )
 

 # Object (message) whose type is JointState
 jstate = JointState()
 # Set values to the message
 jstate.header.stamp = rospy.Time.now()
 jstate.name = jnames
 # Add the head joint value (with value 0) to the joints
 jstate.position = q
 # Loop rate (in Hz)
 rate = rospy.Rate(20)
 # Continuous execution loop
 while not rospy.is_shutdown():
  T = fkine(q)
  x0 = T[0:3,3]
  # Current time (needed for ROS)
  jstate.header.stamp = rospy.Time.now()
  # Publish the message
  pub.publish(jstate)
  bmarker.publish()
  bmarker.xyz(x0)
  
  # Wait for the next iteration
  rate.sleep()
