#Instead of using TAB for indentation, use two spaces at the place of one TAB
#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5,joint_6]
  gains:
    joint_1: {p: 100.0, i: 0.01, d: 0.1}
    joint_2: {p: 100.0, i: 0.01, d: 0.1}
    joint_3: {p: 100.0, i: 0.01, d: 0.1}
    joint_4: {p: 100.0, i: 0.01, d: 0.1}
    joint_5: {p: 100.0, i: 0.01, d: 0.1}
    joint_6: {p: 100.0, i: 0.01, d: 0.1}

#Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_7, joint_8]
  gains:
    joint_7: {p: 50.0, i: 0.01, d: 0.1}
    joint_8: {p: 50.0, i: 0.01, d: 0.1}

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
